# Base image

FROM python:3.10.10-slim-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Working directory
WORKDIR /website

# Installing dependencies and development packages
COPY Pipfile Pipfile.lock /website/
RUN pip install pipenv && pipenv install --dev --system

# Copy project files and directories
COPY . /website/
