# Generated by Django 4.0.5 on 2022-06-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_blogcategory_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="header_image",
            field=models.ImageField(null=True, upload_to="headers"),
        ),
    ]
