# Generated by Django 4.0.6 on 2022-08-10 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_blogpost_header_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="header_image",
        ),
    ]
