# Generated by Django 4.1.3 on 2023-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_blogcategory_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="title",
            field=models.CharField(
                default="Other", max_length=100, unique=True, verbose_name="Title"
            ),
        ),
    ]
